[package]
name = "bmi-rs"
version = "0.0.1"
edition = "2021"

description = "Bindings for the CSDMS Basic Model Interface (BMI)"
readme = "README.md"
authors = ["Austin Raney <araney@lynker.com>"]
license = "MIT"

homepage = "https://github.com/aaraney/bmi-rs"
